# Generated by Django 4.2.9 on 2024-02-23 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("School", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
